apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secrets-store-csi-driver
resources:
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v0.3.0/csidriver.yaml
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v0.3.0/rbac-secretproviderclass.yaml
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v0.3.0/rbac-secretproviderrotation.yaml
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v0.3.0/rbac-secretprovidersyncing.yaml
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v0.3.0/secrets-store-csi-driver-windows.yaml
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v0.3.0/secrets-store-csi-driver.yaml
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v0.3.0/secrets-store.csi.x-k8s.io_secretproviderclasses.yaml
  - https://github.com/kubernetes-sigs/secrets-store-csi-driver/releases/download/v0.3.0/secrets-store.csi.x-k8s.io_secretproviderclasspodstatuses.yaml 
